wandb_version: 1

seed:
  desc: null
  value: 42
embedding_dim:
  desc: null
  value: 32
transformer_layers:
  desc: null
  value: 2
attention_heads:
  desc: null
  value: 4
dropout:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0002
weight_decay:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 25
folds:
  desc: null
  value: 1
early_stopping:
  desc: null
  value: 5
warmup_epochs:
  desc: null
  value: 5
repetition:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745922641.747592
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 5
