wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745617619.517252
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      - 24
      4: 3.11.4
      5: 0.15.8
      8:
      - 5
